# -------------------------------------------------------------------------------------- #
#                            ___ _               ___  ___ ___                            #
#                           | _ |_)_ _  __ _ ___| _ \/ __/ __|                           #
#                           | _ \ | ' \/ _` / -_)   /\__ \__ \                           #
#                           |___/_|_||_\__, \___|_|_\|___/___/                           #
#                                      |___/                                             #
# -------------------------------------------------------------------------------------- #

# SPDX-FileCopyrightText: Simon Schneegans <code@simonschneegans.de>
# SPDX-License-Identifier: CC0-1.0

name: Badges

on:
  push:
    branches:
      - main

jobs:
  update-badges:
    name: Update Badges
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Download cloc
        run: sudo apt-get update -y && sudo apt-get install -y cloc
      - name: Get the Numbers
        run: |
          echo "CODE_LINES=$(tools/cloc.sh --loc)" >> $GITHUB_ENV
          echo "COMMENT_LINES=$(tools/cloc.sh --percentage)" >> $GITHUB_ENV
      - name: Create Lines-of-Code-Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: 981cc7accc7d037aa35d2e0dbbf16632
          filename: loc.json
          label: Lines of Code
          message: ${{ env.CODE_LINES }}
          color: lightgrey
          labelColor: 303030
      - name: Create Comments-Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: 981cc7accc7d037aa35d2e0dbbf16632
          filename: comments.json
          label: Comments
          message: ${{ env.COMMENT_LINES }}%
          valColorRange: ${{ env.COMMENT_LINES }}
          maxColorRange: 50
          minColorRange: 0
          labelColor: 303030
