# SPDX-FileCopyrightText: Simon Schneegans <code@simonschneegans.de>
# SPDX-License-Identifier: CC0-1.0

name: Checks

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Download Dependencies
      run: |
        sudo apt update -qq
        sudo apt install meson -qq
    - name: Build BingeRSS
      run: meson setup build
    - name: Run cargo fmt
      run: cargo fmt --all -- --check

  reuse:
    name: Check Compliance with REUSE Specification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v1
